name: Nextcloud
description: |
  Nextcloud offers a modern, on-premises
  content collaboration platform with real-time
  document editing, video chat & groupware on
  mobile, desktop and web.
logo: nextcloud.svg
